---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage-data
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ca-certificates-data
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-block
