apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data  
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-block
